spring: 
 application:
   name: customer-service
server:
  port: ${PORT:8300}
  
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
endpoints:
   shutdown:
      enabled: true
      sensitive: false
      
account-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9100
    

  