spring:
   application:
      name: zuul-service
server:
   port: ${PORT:8200}
zuul:
   routes:
      account-service:
         path: /account/**
         serviceId: account-service
      order-service:
         path: /order/**
         serviceId: order-service
      product-service:
         path: /product/**
         serviceId: product-service
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
endpoints:
   shutdown:
      enabled: true
      sensitive: false