spring: 
 application:
   name: product-service
server:
     port:8000
     
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
   
endpoints:
  shutdown:
    enabled: true
    sensitive: false
  